export const FETCH_PRODUCTS = 'FETCH_PRODUCTS'
export const ADD_PRODUCTS = 'ADD_PRODUCTS'
export const UPDATE_PRODUCTS = 'UPDATE_PRODUCTS' // DAY LA SAVE
export const EDIT_PRODUCTS = 'EDIT_PRODUCTS' // CON DAY LA LAY PRODUCT MUON EDIT THOY
export const DELETE_PRODUCTS = 'DELETE_PRODUCTS'